language: ruby

os:
  - linux
  - osx

rvm:
  - head
  - 2.3.0
  - 2.2.4
  - jruby-9.0.4.0

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - rvm: head
    - rvm: jruby-9.0.4.0

notifications:
  email: false

env:
  - NO_IPV6_TESTS=1

script:
  - bundle exec rake build
  - bundle exec rake coveralls
